#!/bin/sh

LOG="/var/log/world_writable_fix.log"

for DIR in \
/opt/sbi/wac/integration \
/opt/sbi/wac/lib/appjars \
/opt/sbi/wac/conf/corp_reversefile \
/opt/batchlogs/qsb/smsmandates
do

    TODAY=$(date '+%Y-%m-%d')

    find "$DIR" -type f -mtime 0 -exec ls -dt {} + 2>/dev/null |
    while read FILE
    do
        PERM=$(ls -l "$FILE" | awk '{print $1}')

        case "$PERM" in
            -rw-rw-rw-|-rwxrwxrwx)
                chmod 644 "$FILE"
                echo "$(date): Changed $FILE from $PERM to 644" >> "$LOG"
                ;;
        esac
    done

done




find /your/path -type f -newermt "$(date '+%Y-%m-%d') 00:00:00" ! -newermt "$(date -d 'tomorrow' '+%Y-%m-%d') 00:00:00" -ls


root@cmpmtxn72:~# find /opt/batchlogs/qsb/smsmandates/ -type f -newermt "$(date '+%Y-%m-%d') 00:00:00" ! -newermt "$(date -d 'tomorrow' '+%Y-%m-%d') 00:00:00" -ls
date: illegal option -- d
usage:  date [-u] mmddHHMM[[cc]yy][.SS]
        date [-u] [+format]
        date -a [-]sss[.fff]
find: bad option -newermt
find: [-H | -L] path-list predicate-list
